#!/usr/bin/env python3

from http.server import SimpleHTTPRequestHandler
from socketserver import TCPServer
from sys import argv

class MyHandler(SimpleHTTPRequestHandler):

  def end_headers(self):
    self.send_header('Cache-Control', 'no-cache, no-store, must-revalidate')
    self.send_header('Pragma', 'no-cache')
    self.send_header('Expires', '0')
    SimpleHTTPRequestHandler.end_headers(self)


def main():
  port = 3000 if len(argv) < 2 else int(argv[1])

  with TCPServer(('', port), MyHandler) as httpd:
    print(f'Serving HTTP on port {port} (http://localhost:{port}/) ...')

    try:
      httpd.serve_forever()
    except KeyboardInterrupt:
      pass
    finally:
      httpd.shutdown()
      httpd.server_close()


if __name__ == '__main__':
  main()
